root_dir: ./

stage:
  train: true
  eval: true
  run: true

data:
  low_res: 64
  high_res: 256
  channels: 3
  upscale: 4
  c_frames: 10
  videos: 

model: tecogan

train:
  iterations: 950000
  batch_size: 4
  pretrained_gen: MODEL/2019-12-11 11:26:1/Checkpoints/generator_model_weights_233000.h5 # TecoGAN parameter
  pretrained_disc: # TecoGAN parameter
  sample_freq: 250
  checkpoint_freq: 1000
  info_freq: 100

eval:
  # pretrained_model: MODEL/2019-10-14\ 8\:37\:46/Checkpoints/frvsr_model_weights_18000.h5
  pretrained_gen: 
  pretrained_disc:
  rows: 2
  cols: 2
  video: Video test/8.mp4
  
run:
  pretrained_gen:
  pretrained_disc:
  rows: 2
  cols: 2
  video: Video test/8.mp4
